FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine-2020-12-19

ARG GITREPOBASE="https://github.com/richyrich98765"
ARG GITREPO="test-flask-app"
ARG BRANCH="main"
ARG FOLDERNAME=${GITREPO}-${BRANCH}

RUN apk add --no-cache git && \
    git clone ${GITREPOBASE}/${GITREPO}.git && \
    apk del git && \
    cp -R ${GITREPO}/* . && \
    rm -R ${GITREPO} && \
    pip install -r requirements.txt

ENV STATIC_URL /hello_app/static
ENV STATIC_PATH hello_app/static

EXPOSE 80